dataset_name: "ximerakis19"
sample_file: "input/ximerakis19/metadata/sample_sheet.csv"
cell_annots: "input/ximerakis19/metadata/cell_annots.csv"

target: "gencode_vM25_pc_w500"
bx_whitelist: "extdata/bxs/737K-august-2016.txt"
tech: "10xv2"
strand: "--fr-stranded"

min_umis: 500
