configfile: "download_config.yaml"

import pandas as pd
import os
from glob import glob

# make sure the tmp directory exists
os.makedirs(config['tmp_dir'], exist_ok=True)

print("Loading run data...")
runs = pd.read_csv(config['runs_file'], index_col='run_id')
print("Loaded %d runs." % len(runs.index))

rule all:
    input:
        expand("fastq/{run_id}_1.fastq.gz",
               run_id=runs.index.values)

def get_srr(wildcards):
    return runs.srr[wildcards.run_id]

rule download_fastq:
    output:
        r1="fastq/{run_id}_1.fastq.gz",
        r2="fastq/{run_id}_2.fastq.gz"
        #r3="fastq/{run_id}_3.fastq.gz"
    params:
        srr=get_srr,
        tmp_dir=config['tmp_dir'],
        fq=lambda wcs: config['tmp_dir'] + "/" + wcs.run_id
    threads: 12
    resources:
        mem_mb=1000
    conda:
        "samtools.yaml"
    shell:
        """
        fasterq-dump -e {threads} -S --include-technical -o {params.fq}.fastq -t {params.tmp_dir} {params.srr}
        bgzip -@ {threads} -c {params.fq}_1.fastq > {output.r1}
        rm {params.fq}_1.fastq
        bgzip -@ {threads} -c {params.fq}_2.fastq > {output.r2}
        rm {params.fq}_2.fastq
        if [[ -f "{params.fq}_3.fastq" ]]; then
            rm {params.fq}_3.fastq
        fi
        """
