dataset_name: "dahlin18"
sample_file: "input/dahlin18/sample_sheet.csv"
cell_annots: "input/dahlin18/dahlin18_wolf19_annots.csv.gz"

target: "gencode_vM25_pc_w500"
bx_whitelist: "extdata/bxs/737K-august-2016.txt"
tech: "10xv2"
strand: "--fr-stranded"

min_umis: 500
