dataset_name: "bleckwehl21"
sample_file: "input/bleckwehl21/sample_sheet.csv"
cell_annots: null

target: "utrome_mm10_v2"
bx_whitelist: "extdata/bxs/737K-august-2016.txt"
tech: "10xv2"
strand: "--fr-stranded"

min_umis: 500
